apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  type: {{ .Values.service.type }}
  selector:
    app: demo
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      nodePort: {{ .Values.service.nodePort }}
